--- old/usr/src/lib/fm/libdiskstatus/Makefile	Sat Apr 29 19:27:10 2017
+++ new/usr/src/lib/fm/libdiskstatus/Makefile	Sat Apr 29 19:27:10 2017
@@ -22,7 +22,6 @@
 # Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
-#ident	"%Z%%M%	%I%	%E% SMI"
 
 include		../../Makefile.lib
 include		../Makefile.lib
