--- old/usr/src/lib/fm/libdiskstatus/Makefile	Sat Apr 15 12:44:35 2017
+++ new/usr/src/lib/fm/libdiskstatus/Makefile	Sat Apr 15 12:44:35 2017
@@ -21,8 +21,8 @@
 #
 # Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
+# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
 #
-#ident	"%Z%%M%	%I%	%E% SMI"
 
 include		../../Makefile.lib
 include		../Makefile.lib
@@ -33,6 +33,8 @@
 SUBDIRS=	$(MACH)
 $(BUILD64)SUBDIRS += $(MACH64)
 
+$(RELEASE_BUILD)CPPFLAGS += -DNDEBUG
+
 all :=		TARGET= all
 clean :=	TARGET= clean
 clobber :=	TARGET= clobber
